language: ruby
rvm:
- 2.4.1
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer --assume-extension --only-4xx --url-ignore "https://blog.owo.cloud/feed.xml" --allow-hash-href ./_site
after_success:
- ./bin/auto-deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEPLOY_GIT_NAME: Dean Sheather
  - DEPLOY_GIT_EMAIL: dean@deansheather.com
  - DEPLOY_GIT_SOURCE_BRANCH: master
  - DEPLOY_GIT_BRANCH: gh-pages
